TAB_MAIN = 'Main Tab'
MAIN_CONTENT_CONTAINER = 'Main Content Container'
TOGGLE_FULLSCREEN = 'Toggle fullscreen'
TOGGLE_FULLSCREEN_GRID = 'Toggle fullscreen grid tab'

BUTTON_OPEN_MAIN_SIDEBAR1 = 'Open main sidebar'
OFFCANVAS_MAIN = 'Main offcanvas sidebar'
TAB_SELECTABLE_GRID = "Facility Grid"
TAB_WATER_LEVEL_VIEWER = "Water Level Viewer"
TAB_MF6_INPUTS = 'MF6 inputs'
SELECTABLE_GRID = "Selectable grid figure in the grid/facility tab"
MF6_INPUTS_MAIN_FIG = 'mf6 figure showing a summary of the main inputs'
CLICK_DATA = 'click-data'
POLY_LIST = 'poly_list'
DELETE_INPUT = 'delete_input'
CARD_OUTPUT = 'card_output'
SELECTED_GRID_DATA = 'Selected data from grid'
STORE_SELECTED_GRID_DATA = 'Store the data from the facility selection grid'
STORE_SELECTED_DATA_W_Z_COORD = 'Store selected facility data that includes interpolated z-coordinates'
STORE_FACILITY_DICT = 'Store all the facilities in a dictionary'

WATER_LEVELS = 'Water levels'
SAVE_FIG = 'Save figure'
OPEN_FIG = 'Open a figure'
STORE_OPENED_FIG = 'Store the opened fig'
SAVE_FIG_NONRESAMPLED = 'Save nonresampled figure'
EXCEL_UPLOAD = 'Excel upload'
READ_EXCEL = 'Read Excel'
STORE_EXCEL = 'Store Excel'
STORE_FIG = 'Store fig'
STORE_FIGTOSAVE = 'Store fig to save as json'

PROGRESS_EXCEL = 'Excel read progress bar'
PROGRESS_INTERVAL = 'Progress bar interval'
STORE_PROGRESS = '0'
STORE_SRTSTP_PROGRESS = ''
TRACE_NAME_TITLE = 'Title of Trace Name Card'
STORE_TRACE_NAME = 'Store trace name'
COLOR_PICKER_TRACE = 'Color picker for traces'
COLOR_PICKER_BUTTON = 'Color picker button'
TRACE_COLOR = 'black'
STORE_COLOR_PICKER_VALUE = 'Store Color picker value'
TRACE_UPDATER_WL = 'Trace updator for the water level figure'
DROPDOWN_LINE_SOLID = 'solid dropdownmenu item'
DROPDOWN_LINE_DASH = 'dash dropdownmenu item'

BUTTON_GROUP_XAXIS = 'x-axis button group'
BUTTON_GROUP_YAXIS = 'y-axis button group'

DATA_RETURN = 'Returned Data Display'
BUTTON_OPEN_MAIN_SIDEBAR2 = 'Sidebar 2 button'
OFFCANVAS_MAIN2 = '2nd offcanvas for data display'
